ShowFlixApp/Controllers/ShowStreamingController.cs
using Microsoft.AspNetCore.Mvc;
using ShowFlixApp.Models;

namespace ShowFlixApp.Controllers
{
    public class ShowStreamingController : Controller
    {
        SQLServerShowRepository repo = new SQLServerShowRepository();
        public IActionResult Index()
        {
           
            return View(repo.ShowsStreaming());
        }

        public IActionResult StreamingDetail(int streamId)
        {
            ShowStreaming streaming = repo.ShowsStreaming().Find(r => r.StreamId == streamId);
            return View(streaming);
        }

        public IActionResult DeleteStreaming(int streamId)
        {
            ShowStreaming streaming = repo.ShowsStreaming().Find(r => r.StreamId == streamId);
            return View(streaming);
        }
    }
}

ShowFlixApp/Controllers/ShowsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShowFlixApp.Models;
using System.Collections.Generic;
using System.IO;

namespace ShowFlixApp.Controllers
{
    public class ShowsController : Controller
    {
       
        private readonly IHostingEnvironment environment;
        private readonly IShowsRepository repo;

        public ShowsController(IHostingEnvironment environment,IShowsRepository repo)
        {
            this.environment = environment;
            this.repo = repo;
            
        }
        public IActionResult Index()
        {
          
            List<Show> shows = repo.GetAllShows();
          ViewBag.PageTitle = "Show Details From ShowFlix";
             return View(shows);
        }

        public IActionResult GetShow(int showId)
        {
           
            Show show = repo.GetShowById(showId);
            return View(show);
        }
    
  public IActionResult DeleteShow(int showId)
        {
           
            Show show = repo.GetShowById(showId);
            return View(show);
        }

        public IActionResult Yes(int showId)
        {
            
            repo.DeleteShow(showId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateShow()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateShow(Show show,IFormFile file)
        {
            string wwwPath = this.environment.WebRootPath;// wwwroot/

            string contentPath = Path.Combine(this.environment.WebRootPath, "images");
            string fileName = Path.GetFileName(file.FileName);
            using (FileStream stream = new FileStream(Path.Combine(contentPath, fileName), FileMode.Create))
            {
                file.CopyTo(stream);
                show.ShowImg = "images/" + file.FileName;
            }

         
            repo.AddNewShow(show);
            return RedirectToAction("Index");
        }
    }
}

ShowFlixApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShowFlixApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="bg-primary">
        <nav class="bg-primary navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container bg-info">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShowFlixApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shows" asp-action="Index">Shows</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShowStreaming" asp-action="Index">Show Streaming</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShowFlixApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShowFlixApp/Views/Shared/_StreamDetail.cshtml
@model ShowFlixApp.Models.ShowStreaming


<p class="alert alert-heading"> Show Streaming Details : @Model.Show.ShowName</p>


<div class="card col-sm-3">
    <div class="card-body">
    <div class="card-text">
    Show Date and Time :    @Model.ShowDateTime<br/>
    Duration :    @Model.DurationInMinutes
    </div>
</div>

@if((string)ViewData["ViewName"]=="Delete")
    {
        <div class="card-footer">
  <p>Are you sure to delete the Streaming ? <a asp-action="Yes" class="btn btn-sm btn-primary">Yes</a>
  <a asp-action="Index" class="btn btn-sm btn-danger">No</a>    
  
  </p>
        </div>
    }
    else
    {
        <div class="card-footer">
    <a asp-action="Index" class="btn btn-primary"> Back To All Shows</a>
</div>
    }
</div>