ShowFlixApp/Models/Show.cs
namespace ShowFlixApp.Models
{
    public class Show
    {
        public int ShowId { get; set; }
        public string ShowName { get; set; }
        public string Category { get; set; }
        public string Language { get; set; }
        public string LeadActors { get; set; }
        public string ShowImg { get; set; }
    }
}

ShowFlixApp/Controllers/ShowsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShowFlixApp.Models;
using System.Collections.Generic;
using System.IO;

namespace ShowFlixApp.Controllers
{
    public class ShowsController : Controller
    {
       
        private readonly IHostingEnvironment environment;
        private readonly IShowsRepository repo;

        public ShowsController(IHostingEnvironment environment,IShowsRepository repo)
        {
            this.environment = environment;
            this.repo = repo;
            
        }
        public IActionResult Index()
        {
          
            List<Show> shows = repo.GetAllShows();
          ViewBag.PageTitle = "Show Details From ShowFlix";
             return View(shows);
        }

        public IActionResult GetShow(int showId)
        {
           
            Show show = repo.GetShowById(showId);
            return View(show);
        }
    
  public IActionResult DeleteShow(int showId)
        {
           
            Show show = repo.GetShowById(showId);
            return View(show);
        }

        public IActionResult Yes(int showId)
        {
            
            repo.DeleteShow(showId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateShow()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateShow(Show show,IFormFile file)
        {
            string wwwPath = this.environment.WebRootPath;// wwwroot/

            string contentPath = Path.Combine(this.environment.WebRootPath, "images");
            string fileName = Path.GetFileName(file.FileName);
            using (FileStream stream = new FileStream(Path.Combine(contentPath, fileName), FileMode.Create))
            {
                file.CopyTo(stream);
                show.ShowImg = "images/" + file.FileName;
            }

         
            repo.AddNewShow(show);
            return RedirectToAction("Index");
        }
    }
}

ShowFlixApp/ViewComponents/ShowViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShowFlixApp.Models;
using System.Threading.Tasks;

namespace ShowFlixApp.ViewComponents
{
    public class ShowViewComponent:ViewComponent
    {
        SQLServerShowRepository repo = new SQLServerShowRepository();
        public IViewComponentResult Invoke(int showId,string viewName)
        {
            ViewData["ViewName"] = viewName;
            return  View(repo.GetShowById(showId));
        }
    }
}

ShowFlixApp/Views/Shows/CreateShow.cshtml
@model ShowFlixApp.Models.Show

<br/>
<br/>
<br/>
<br/>
<form asp-action="CreateShow" method="post" enctype="multipart/form-data">
    <div class="form-group w-25">
    <label>Show Name</label>

    <input   asp-for=ShowName    class="form-control" id="txtShowName">


  </div>
  <div class="form-group w-25">
    <label>Category :</label>

    <input asp-for=Category class="form-control" id="txtCategory">

  </div>
  <div class="form-group w-25">
    <label>Language</label>

    <input class="form-control" asp-for=Language id="txtLanguage">

  </div>
  <div class="form-group w-25">
    <label>Lead Actors :</label>

    <input asp-for=LeadActors  class="form-control" id="txtLeadActor">

  </div>

  <div class="form-group w-25">
    <label>Upload the Show Image :</label>
    
      <input type="file" name="file"/>

  </div>


  
  <button type="submit" class="btn btn-secondary">Submit</button>

</form>

ShowFlixApp/Views/Shows/DeleteShow.cshtml
@model ShowFlixApp.Models.Show








@await Component.InvokeAsync("Show", new {showId=@Model.ShowId,viewName="Delete"})



















@*
   *@

ShowFlixApp/Views/Shows/GetShow.cshtml
@model ShowFlixApp.Models.Show



@await Component.InvokeAsync("Show",new {showId=@Model.ShowId,viewName="Details"})

@*    <div class="card-footer">
        <a asp-action="Index" class="btn btn-primary">Back to Shows</a>
    </div>*@

ShowFlixApp/Views/Shows/Index.cshtml
@model IEnumerable<ShowFlixApp.Models.Show>

<p class="alert alert-primary text-center display-4">
 @ViewBag.PageTitle
</p>

<a asp-action="CreateShow" class="btn btn-secondary">Create New</a>

<br/>
<br/>
<table class="table table-bordered w-75">
    <tr>
        <th>Show Name</th>
        <th>Category</th>
        <th>Language</th>
        <th>Lead Actors</th>
        <th>Action</th>
           <th>Action</th>
    </tr>

@*    Razor syntax
*@   
@foreach(var item in Model)
    {
        <tr>
            <td>@item.ShowName</td>
            <td>@item.Category</td>
            <td>@item.Language</td>
            <td>@item.LeadActors</td>
            <td><a  asp-action="GetShow" asp-route-showId="@item.ShowId" class="btn btn-warning">Details</a></td>
            <td><a asp-action="DeleteShow" class="btn btn-danger" asp-route-showId="@item.ShowId"> Delete</a> </td>
        </tr>
    }

</table>